from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol


@dataclass
class MemoryContext:
    text: str = ""
    claims: list[dict[str, object]] = field(default_factory=list)
    session_evidence: list[dict[str, object]] = field(default_factory=list)
    snapshot_hash: str = ""


@dataclass
class CompressionMemoryContribution:
    flushed_event_ids: list[int] = field(default_factory=list)
    memory_units_created: list[dict[str, object]] = field(default_factory=list)
    compression_hints: list[str] = field(default_factory=list)


class MemoryProvider(Protocol):
    @property
    def name(self) -> str: ...
    def initialize(self, *, subject_id: str, session_id: str, profile_id: str, workspace_id: str, agent_context: str) -> None: ...
    def static_prompt_block(self) -> str: ...
    def prefetch(self, query: str, *, session_id: str, token_budget: int) -> MemoryContext: ...
    def queue_prefetch(self, query: str, *, session_id: str) -> None: ...
    def sync_turn(self, user_content: str, assistant_content: str, *, session_id: str, messages: list[dict]) -> None: ...
    def on_session_end(self, messages: list[dict]) -> None: ...
    def on_session_switch(self, new_session_id: str, *, parent_session_id: str = "", reset: bool = False, rewound: bool = False) -> None: ...
    def on_pre_compress(self, messages: list[dict]) -> CompressionMemoryContribution: ...
    def on_memory_write(self, plan: dict[str, object], result: dict[str, object]) -> None: ...
    def shutdown(self) -> None: ...
